### ISSUE TITLE
[Slicing] Home - Sidebar untuk Nav di Mobile

### ISSUE THREAD

**Issue by ardianta** [lotengdev/lotengdev-web#10]
![image](https://user-images.githubusercontent.com/4420029/197936566-7a277d68-9ede-4763-8f4f-1a51fe29eb98.png)

Note:
- Cuma slicing sidebar nav untuk tampilan di mobile
- Sidenav tampil saat humberger menu diklik

**Comment by mahenoorsalat** [comment]
I want to work on this issue :) Assign me please 👍  @ardianta

**Comment by ardianta** [comment]
Okay
