### ISSUE TITLE
Add a "How to Contribute" Section in README.md

### ISSUE THREAD

**Issue by Snehshishdutta** [lotengdev/lotengdev-web#27]
Suggestion to Add a "How to Contribute" Section in README.md

I think a "How to Contribute" section in the README.md file would be a great addition. This section could provide new contributors with a clear guide on how to get involved, including steps like:

1.Setting up the project locally
2.Finding good first issues
3.Coding standards or style guidelines
4.Creating pull requests

Adding these details could make it easier for new contributors to get started and increase overall contributions to the project. Can u assign this issue to me under hacktoberfest label?

**Comment by ardianta** [comment]
Hi @Snehshishdutta, thanks for the suggestion. Thats great, I assign to you.

**Comment by Snehshishdutta** [comment]
Thanks, @ardianta  Appreciate the opportunity. I'll get started on drafting the "How to Contribute" section and make sure it covers all the essential points for new contributors.
