### ISSUE TITLE
[BUG]: In small screen navigation not working

### ISSUE THREAD

**Issue by basavarajakj** [lotengdev/lotengdev-web#32]
## In Small screen navigation to different screens hamburger menu is not clickable.

![image](https://github.com/user-attachments/assets/37646b4e-8c43-4f1e-8437-79161803d8cd)

### Feel free to assign I will fix this ASAP

Cheers🥂! 
Happy Coding!

**Comment by ardianta** [comment]
I think the work in progress at #10
